flowerbed: flowerbed.c
	gcc flowerbed.c -o flowerbed
gardener: gardener.c
	gcc gardener.c -o gardener
manager:manager.c
	gcc manager.c -o manager
all:flowerbed gardener manager

clean:
	rm flowerbed gardener manager